# Generated by Django 5.1 on 2024-08-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("username", models.UUIDField(primary_key=True, serialize=False)),
                ("fullname", models.CharField(max_length=20)),
                ("gmail", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=400)),
            ],
        ),
    ]
