# Generated by Django 5.1 on 2024-08-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Movie", "0004_alter_user_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="otp",
            field=models.IntegerField(default=333),
        ),
    ]
